### ISSUE TITLE
tree-v1.8.0 didn't exist on Steve Baker's resources (HTTP/404)

### ISSUE THREAD

**Issue by JuPlutonic** [rsdoiel/tree-v1.7.0#1]
Not accessible:
http://mama.indstate.edu/users/ice/tree/
ftp://mama.indstate.edu/linux/tree/

Faraway for
url "http://mama.indstate.edu/users/ice/tree/src/tree-1.8.0.tgz"
sha256 "715d5d4b434321ce74706d0dd067505bb60c5ea83b5f0b3655dae40aa6f9b7c2"

LinuxOnScratch, Linuxbrew have only recipes and haven't got sources and binaries("bottles"): Debian, Fedora and Arch only have got binaries of tree-1.8.0.

Can you ask somebody to provide 1.8.0 sources here on GitHub?
P.S. Sorry for my English.

Huh, here I found
`http://deb.debian.org/debian/pool/main/t/tree/tree_1.8.0.orig.tar.gz`

**Comment by rsdoiel** [comment]
Hello,

I'm sorry I don't know the author of the original code I simply did a Google search and came up with the v1.7.0 source and compiled it.  I'm always forgetting where I find these types of tools so I made a fork. I wish I could be of more help. You might want to check the Debian maintainer's email list or IRC and see if anyone knows there.

All the best,

Robert Doiel
